// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package org.apache.commons.httpclient;


// Referenced classes of package org.apache.commons.httpclient:
//            NameValuePair, HeaderElement, HttpException

public class Header extends NameValuePair
{

    private boolean isAutogenerated;

    public Header()
    {
        this(null, null);
    }

    public Header(String s, String s1)
    {
        super(s, s1);
        isAutogenerated = false;
    }

    public Header(String s, String s1, boolean flag)
    {
        super(s, s1);
        isAutogenerated = false;
        isAutogenerated = flag;
    }

    public HeaderElement[] getElements()
    {
        return HeaderElement.parseElements(getValue());
    }

    public HeaderElement[] getValues()
        throws HttpException
    {
        return HeaderElement.parse(getValue());
    }

    public boolean isAutogenerated()
    {
        return isAutogenerated;
    }

    public String toExternalForm()
    {
        StringBuffer stringbuffer = new StringBuffer();
        String s;
        if (getName() == null)
        {
            s = "";
        } else
        {
            s = getName();
        }
        stringbuffer = stringbuffer.append(s).append(": ");
        if (getValue() == null)
        {
            s = "";
        } else
        {
            s = getValue();
        }
        return stringbuffer.append(s).append("\r\n").toString();
    }

    public String toString()
    {
        return toExternalForm();
    }
}
